"""Selecting which instances to run.

Phase 4 runs the same 86-instance split three times, so the runner needs a split
entry point. It also needs to run the split in batches, because a single arm takes
around 14 hours and `--refine-output` cannot resume mid-directory.
"""

import pytest

from src.agents import sql_agent_runner as runner


SPLIT_BODY = """# Generated by scripts/make_splits.py. Do not edit by hand.
# test = the rest.
local001
local002

local003
local004
local005
"""

IDS = ["local001", "local002", "local003", "local004", "local005"]


@pytest.fixture
def split_file(tmp_path):
    path = tmp_path / "test_split.txt"
    path.write_text(SPLIT_BODY, encoding="utf-8")
    return str(path)


def _args(*argv):
    return runner._build_parser().parse_args(list(argv))


def _ids(*argv):
    return runner._requested_instance_ids(_args(*argv))


class TestSelectors:
    def test_split_returns_the_file_ids_without_comments_or_blanks(self, split_file):
        assert _ids("--split", split_file) == IDS

    def test_instance_id_is_still_honoured(self):
        assert _ids("--instance-id", "local074", "--instance-id", "local025") == [
            "local074",
            "local025",
        ]

    def test_run_all_from_file_means_every_instance(self):
        assert _ids("--run-all-from-file") is None

    def test_no_selector_is_an_error(self):
        with pytest.raises(ValueError, match="--split"):
            _ids()


class TestMutualExclusion:
    """Silently preferring one selector would run the wrong instance set."""

    def test_split_conflicts_with_instance_id(self, split_file):
        with pytest.raises(ValueError, match="mutually exclusive"):
            _ids("--split", split_file, "--instance-id", "local074")

    def test_split_conflicts_with_run_all(self, split_file):
        with pytest.raises(ValueError, match="mutually exclusive"):
            _ids("--split", split_file, "--run-all-from-file")

    def test_instance_id_conflicts_with_run_all(self):
        with pytest.raises(ValueError, match="mutually exclusive"):
            _ids("--instance-id", "local074", "--run-all-from-file")


class TestBatching:
    def test_offset_skips_from_the_front(self, split_file):
        assert _ids("--split", split_file, "--split-offset", "2") == IDS[2:]

    def test_limit_caps_the_batch(self, split_file):
        assert _ids("--split", split_file, "--split-limit", "2") == IDS[:2]

    def test_offset_and_limit_together(self, split_file):
        assert _ids("--split", split_file, "--split-offset", "1", "--split-limit", "3") == IDS[1:4]

    def test_limit_beyond_the_remainder_returns_what_is_left(self, split_file):
        """The last batch is short; that is not an error."""
        assert _ids("--split", split_file, "--split-offset", "3", "--split-limit", "99") == IDS[3:]

    def test_offset_past_the_end_is_an_error(self, split_file):
        """Silently running zero instances would waste a batch slot."""
        with pytest.raises(ValueError, match="beyond"):
            _ids("--split", split_file, "--split-offset", "5")

    def test_negative_offset_is_an_error(self, split_file):
        with pytest.raises(ValueError, match="negative"):
            _ids("--split", split_file, "--split-offset", "-1")

    def test_zero_limit_is_an_error(self, split_file):
        with pytest.raises(ValueError, match="positive"):
            _ids("--split", split_file, "--split-limit", "0")

    def test_batching_without_split_is_an_error(self):
        with pytest.raises(ValueError, match="--split"):
            _ids("--instance-id", "local074", "--split-offset", "1")


class TestMissingFile:
    def test_missing_split_file_names_the_path(self, tmp_path):
        missing = str(tmp_path / "nope.txt")
        with pytest.raises(FileNotFoundError, match="nope.txt"):
            _ids("--split", missing)


class TestParserDefaults:
    def test_split_options_default_to_unset(self):
        args = _args("--instance-id", "local074")
        assert args.split is None
        assert args.split_offset == 0
        assert args.split_limit is None
