"""Train/test split construction and loading.

The paper (Table 11) gives only the split sizes, not the instance ids, so the
split is generated locally and must be reproducible from a recorded seed.
"""

import pytest

from src.utils.splits import load_split, make_split, write_split

IDS = [f"local{i:03d}" for i in range(1, 21)]


class TestMakeSplit:
    def test_sizes_match_request(self):
        train, test = make_split(IDS, train_size=6, seed=0)

        assert len(train) == 6
        assert len(test) == len(IDS) - 6

    def test_train_and_test_are_disjoint(self):
        train, test = make_split(IDS, train_size=6, seed=0)

        assert set(train).isdisjoint(test)

    def test_union_covers_every_input_id(self):
        train, test = make_split(IDS, train_size=6, seed=0)

        assert set(train) | set(test) == set(IDS)

    def test_same_seed_reproduces_the_split(self):
        first = make_split(IDS, train_size=6, seed=7)
        second = make_split(IDS, train_size=6, seed=7)

        assert first == second

    def test_different_seed_changes_the_split(self):
        """Guards against a shuffle that silently does nothing."""
        a, _ = make_split(IDS, train_size=6, seed=0)
        b, _ = make_split(IDS, train_size=6, seed=1)

        assert a != b

    def test_input_order_does_not_affect_the_split(self):
        forward = make_split(IDS, train_size=6, seed=0)
        reversed_input = make_split(list(reversed(IDS)), train_size=6, seed=0)

        assert forward == reversed_input

    def test_outputs_are_sorted_for_stable_diffs(self):
        train, test = make_split(IDS, train_size=6, seed=0)

        assert train == sorted(train)
        assert test == sorted(test)

    def test_train_size_may_equal_the_population(self):
        train, test = make_split(IDS, train_size=len(IDS), seed=0)

        assert len(train) == len(IDS)
        assert test == []

    @pytest.mark.parametrize("train_size", [-1, 21])
    def test_out_of_range_train_size_is_rejected(self, train_size):
        with pytest.raises(ValueError):
            make_split(IDS, train_size=train_size, seed=0)

    def test_duplicate_ids_are_rejected(self):
        """A duplicated id signals an upstream data problem, not something to paper over."""
        with pytest.raises(ValueError):
            make_split(IDS + [IDS[0]], train_size=6, seed=0)

    def test_empty_population_is_rejected(self):
        with pytest.raises(ValueError):
            make_split([], train_size=0, seed=0)


class TestSplitFileRoundTrip:
    def test_write_then_load_returns_the_same_ids(self, tmp_path):
        path = tmp_path / "train.txt"
        train, _ = make_split(IDS, train_size=6, seed=0)

        write_split(path, train)

        assert load_split(path) == train

    def test_load_ignores_blank_lines_and_comments(self, tmp_path):
        path = tmp_path / "train.txt"
        path.write_text(
            "# generated by scripts/make_splits.py\n"
            "\n"
            "local001\n"
            "   local002   \n"
            "\n"
            "# trailing note\n",
            encoding="utf-8",
        )

        assert load_split(path) == ["local001", "local002"]

    def test_load_rejects_duplicates(self, tmp_path):
        path = tmp_path / "train.txt"
        path.write_text("local001\nlocal001\n", encoding="utf-8")

        with pytest.raises(ValueError):
            load_split(path)

    def test_load_missing_file_raises(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            load_split(tmp_path / "absent.txt")
