#!/usr/bin/env python3
"""Generate the DataClaw train/test split files.

Stratifies the 492 DataClaw tasks by (category, level), puts half of each
stratum in test and halves train again into train_a (run first) and train_b
(run only if train_a yields too few trajectories). Prints per-stratum counts
and how many development-set tasks land in each file.

    python scripts/dataclaw_make_split.py [--seed 0]
"""

import argparse
import csv
import sys
from collections import Counter
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))

from src.utils.splits import write_split  # noqa: E402
from tkstore.dataclaw.split import split_tasks, task_strata  # noqa: E402

DEFAULT_TASKS_DIR = Path.home() / "DataClaw" / "tasks"
SPLIT_DIR = _REPO_ROOT / "data" / "splits"
MANIFEST = _REPO_ROOT / "data" / "dataclaw_dev" / "manifest.csv"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--tasks-dir", type=Path, default=DEFAULT_TASKS_DIR)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--out-dir", type=Path, default=SPLIT_DIR)
    args = parser.parse_args()

    strata = task_strata(args.tasks_dir)
    split = split_tasks(strata, seed=args.seed)

    header = (
        "Generated by scripts/dataclaw_make_split.py. Do not edit by hand.\n"
        f"Stratified by (category, level), seed={args.seed}. test = half of every\n"
        "stratum; train_a and train_b halve the rest the same way."
    )
    parts = {"test": split.test, "train_a": split.train_a, "train_b": split.train_b}
    for name, ids in parts.items():
        path = write_split(args.out_dir / f"dataclaw_{name}.txt", ids, header)
        print(f"wrote {path} ({len(ids)} tasks)")

    counts = {name: Counter(strata[t] for t in ids) for name, ids in parts.items()}
    print(f"\n{'category':<38}{'level':<8}{'total':>6}" + "".join(f"{n:>9}" for n in parts))
    for stratum in sorted(set(strata.values())):
        total = sum(c[stratum] for c in counts.values())
        print(f"{stratum[0]:<38}{stratum[1]:<8}{total:>6}" + "".join(f"{counts[n][stratum]:>9}" for n in parts))

    if MANIFEST.is_file():
        with MANIFEST.open(encoding="utf-8", newline="") as f:
            dev = {row["task_id"] for row in csv.DictReader(f)}
        print(f"\ndevelopment-set tasks ({len(dev)}): " + ", ".join(
            f"{name} {len(dev & set(ids))}" for name, ids in parts.items()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
