#!/usr/bin/env python3
"""Generate the Spider2-SQLite split files.

The split is decided by data availability, not a seed. Algorithm 3 needs the gold
SQL `s*`, but Spider2-lite publishes it for only 24 of the 135 SQLite instances
while publishing gold *results* for all 135. So instances with gold SQL become
train and the rest become test, which is also why evaluation is unaffected.

A third file records the subset of test instances that the upstream reference
store (`tkstore/tkstore_sqlite.csv`) was not trained on. Evaluating that store is
only honest on this subset; our own store is evaluated on the full test set.

    python scripts/make_splits.py
"""

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))

from src.utils.splits import (  # noqa: E402
    load_store_instance_ids,
    partition_by_gold_sql,
    uncontaminated_subset,
    write_split,
)

JSONL_PATH = _REPO_ROOT / "data" / "spider2-lite.jsonl"
MAP_PATH = _REPO_ROOT / "data" / "spider2_local_map.json"
GOLD_SQL_DIR = _REPO_ROOT / "evaluation" / "gold" / "sql"
REFERENCE_STORE = _REPO_ROOT / "tkstore" / "tkstore_sqlite.csv"
SPLIT_DIR = _REPO_ROOT / "data" / "splits"


def load_sqlite_instance_ids() -> list:
    """Spider2 instance ids that run on SQLite (the `local*` prefix, per infer_engine)."""
    ids = []
    with open(JSONL_PATH, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            instance_id = json.loads(line).get("instance_id", "")
            if instance_id.startswith("local"):
                ids.append(instance_id)
    return ids


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gold-sql-dir", type=Path, default=GOLD_SQL_DIR)
    parser.add_argument("--reference-store", type=Path, default=REFERENCE_STORE)
    args = parser.parse_args()

    instance_ids = load_sqlite_instance_ids()
    print(f"SQLite instances in {JSONL_PATH.name}: {len(instance_ids)}")

    train, test = partition_by_gold_sql(instance_ids, args.gold_sql_dir)
    reference_ids = load_store_instance_ids(args.reference_store)
    subset = uncontaminated_subset(test, reference_ids)

    provenance = (
        "Generated by scripts/make_splits.py. Do not edit by hand.\n"
        "train = the SQLite instances whose gold SQL is published, because\n"
        "Algorithm 3 needs it; test = the rest. Gold results exist for all 135\n"
        "instances, so evaluation covers the whole test set."
    )
    subset_provenance = (
        "Generated by scripts/make_splits.py. Do not edit by hand.\n"
        "Test instances that tkstore/tkstore_sqlite.csv was NOT trained on.\n"
        "Use this subset when evaluating that upstream reference store; our own\n"
        "store is evaluated on the full test set."
    )

    train_path = write_split(SPLIT_DIR / "spider2_sqlite_train.txt", train, provenance)
    test_path = write_split(SPLIT_DIR / "spider2_sqlite_test.txt", test, provenance)
    subset_path = write_split(
        SPLIT_DIR / "spider2_sqlite_test_no_reference_leak.txt", subset, subset_provenance
    )

    print(f"wrote {train_path.relative_to(_REPO_ROOT)} ({len(train)} ids)")
    print(f"wrote {test_path.relative_to(_REPO_ROOT)} ({len(test)} ids)")
    print(f"wrote {subset_path.relative_to(_REPO_ROOT)} ({len(subset)} ids)")
    print(
        f"\nreference store {args.reference_store.name} trained on {len(reference_ids)} instances; "
        f"{len(set(reference_ids) & set(train))} land in train, "
        f"{len(test) - len(subset)} are excluded from its evaluation subset"
    )

    _report_database_coverage(train, test)
    return 0


def _report_database_coverage(train: list, test: list) -> None:
    """How much database overlap the split gives, which bounds db-scoped rule reuse."""
    mapping = json.loads(MAP_PATH.read_text(encoding="utf-8"))
    train_dbs = Counter(mapping[i] for i in train if i in mapping)
    test_dbs = Counter(mapping[i] for i in test if i in mapping)
    shared = set(train_dbs) & set(test_dbs)
    reachable = sum(count for db, count in test_dbs.items() if db in shared)

    print("\ndatabase coverage")
    print(f"  databases with >=1 train instance: {len(train_dbs)}/{len(set(mapping.values()))}")
    print(f"  databases present in both splits:  {len(shared)}")
    print(
        f"  test instances whose database has a train instance: "
        f"{reachable}/{len(test)} ({reachable / len(test):.0%})"
    )
    print("  (upper bound on how many test instances db-scoped rules can reach;")
    print("   the rest must rely on generic rules)")


if __name__ == "__main__":
    raise SystemExit(main())
