#!/usr/bin/env python3
"""Generate BIRD mini-dev instance ids and the train/test split files.

BIRD mini-dev SQLite has 500 JSON rows; two pairs are exact duplicates, so the
population is 498. Instance ids are ``minidev0000`` … ``minidev0497`` in JSON
order after that dedup. The split is a seeded random 25%/75% (seed 0 → 124/374).
A first-round evaluation subsample is 1/3 of test (125 ids), also seed 0.

    python scripts/make_bird_splits.py
"""

import argparse
import csv
import sys
from collections import Counter
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))

from src.utils.bird import (  # noqa: E402
    TRAIN_FRACTION,
    TRAIN_SEED,
    index_fields,
    load_minidev_records,
    write_bird_jsonl,
)
from src.utils.splits import make_split, write_split  # noqa: E402

BIRD_JSON = _REPO_ROOT / "data" / "minidev" / "MINIDEV" / "mini_dev_sqlite.json"
SPLIT_DIR = _REPO_ROOT / "data" / "splits"


def write_index(path: Path, records: list) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f, fieldnames=["instance_id", "question_id", "db_id", "difficulty"]
        )
        writer.writeheader()
        for record in records:
            writer.writerow(index_fields(record))
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bird-json", type=Path, default=BIRD_JSON)
    parser.add_argument("--split-dir", type=Path, default=SPLIT_DIR)
    parser.add_argument(
        "--jsonl-path",
        type=Path,
        default=_REPO_ROOT / "data" / "bird_minidev.jsonl",
    )
    args = parser.parse_args()

    records = load_minidev_records(args.bird_json)
    ids = [r["instance_id"] for r in records]
    train_size = round(len(ids) * TRAIN_FRACTION)
    train, test = make_split(ids, train_size=train_size, seed=TRAIN_SEED)
    test_sub_size = round(len(test) / 3)
    test_sub, _ = make_split(test, train_size=test_sub_size, seed=TRAIN_SEED)

    provenance = (
        "Generated by scripts/make_bird_splits.py. Do not edit by hand.\n"
        "Population = BIRD mini-dev SQLite after exact-row dedup (498 ids).\n"
        f"train/test = random {TRAIN_FRACTION:.0%}/{100 - TRAIN_FRACTION * 100:.0%} "
        f"with seed={TRAIN_SEED}."
    )
    sub_provenance = (
        "Generated by scripts/make_bird_splits.py. Do not edit by hand.\n"
        "First-round evaluation subsample: random 1/3 of bird_minidev_test.txt, "
        f"seed={TRAIN_SEED}."
    )

    jsonl_path = write_bird_jsonl(args.jsonl_path, records)
    index_path = write_index(args.split_dir / "bird_minidev_index.csv", records)
    train_path = write_split(args.split_dir / "bird_minidev_train.txt", train, provenance)
    test_path = write_split(args.split_dir / "bird_minidev_test.txt", test, provenance)
    sub_path = write_split(
        args.split_dir / "bird_minidev_test_sub.txt", test_sub, sub_provenance
    )

    print(f"instances after dedup: {len(ids)}")
    print(f"wrote {jsonl_path.relative_to(_REPO_ROOT)} ({len(records)} rows)")
    print(f"wrote {index_path.relative_to(_REPO_ROOT)} ({len(records)} rows)")
    print(f"wrote {train_path.relative_to(_REPO_ROOT)} ({len(train)} ids)")
    print(f"wrote {test_path.relative_to(_REPO_ROOT)} ({len(test)} ids)")
    print(f"wrote {sub_path.relative_to(_REPO_ROOT)} ({len(test_sub)} ids)")
    _report_database_coverage(records, train, test)
    return 0


def _report_database_coverage(records: list, train: list, test: list) -> None:
    db_of = {r["instance_id"]: r["db_id"] for r in records}
    train_dbs = Counter(db_of[i] for i in train)
    test_dbs = Counter(db_of[i] for i in test)
    shared = set(train_dbs) & set(test_dbs)
    reachable = sum(count for db, count in test_dbs.items() if db in shared)
    print("\ndatabase coverage")
    print(f"  databases with >=1 train instance: {len(train_dbs)}/{len(set(db_of.values()))}")
    print(f"  test instances whose database has a train instance: {reachable}/{len(test)}")
    print("  train per database:")
    for db, count in sorted(train_dbs.items()):
        print(f"    {db}: {count}")


if __name__ == "__main__":
    raise SystemExit(main())
