#!/usr/bin/env python3
"""Generate the Spider2-SQLite train/test split files.

Sizes follow the paper's Table 11 (135 total = 34 train + 101 test). The paper
does not publish the instance ids, so the split comes from the seed recorded
below and in data/splits/README.md.

    python scripts/make_splits.py [--seed 0] [--train-size 34]
"""

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))

from src.utils.splits import make_split, write_split  # noqa: E402

JSONL_PATH = _REPO_ROOT / "data" / "spider2-lite.jsonl"
MAP_PATH = _REPO_ROOT / "data" / "spider2_local_map.json"
SPLIT_DIR = _REPO_ROOT / "data" / "splits"


def load_sqlite_instance_ids() -> list:
    """Spider2 instance ids that run on SQLite (the `local*` prefix, per infer_engine)."""
    ids = []
    with open(JSONL_PATH, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            instance_id = json.loads(line).get("instance_id", "")
            if instance_id.startswith("local"):
                ids.append(instance_id)
    return ids


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--train-size", type=int, default=34)
    args = parser.parse_args()

    instance_ids = load_sqlite_instance_ids()
    print(f"SQLite instances in {JSONL_PATH.name}: {len(instance_ids)}")

    train, test = make_split(instance_ids, train_size=args.train_size, seed=args.seed)

    provenance = (
        f"Generated by scripts/make_splits.py (seed={args.seed}, "
        f"train_size={args.train_size}).\n"
        "Sizes follow the paper's Table 11; the instance ids are ours because the\n"
        "paper does not publish its split. Do not edit by hand."
    )
    train_path = write_split(SPLIT_DIR / "spider2_sqlite_train.txt", train, provenance)
    test_path = write_split(SPLIT_DIR / "spider2_sqlite_test.txt", test, provenance)
    print(f"wrote {train_path.relative_to(_REPO_ROOT)} ({len(train)} ids)")
    print(f"wrote {test_path.relative_to(_REPO_ROOT)} ({len(test)} ids)")

    _report_database_coverage(train, test)
    return 0


def _report_database_coverage(train: list, test: list) -> None:
    """How much database overlap the split gives, which bounds db-scoped rule reuse."""
    mapping = json.loads(MAP_PATH.read_text(encoding="utf-8"))
    train_dbs = Counter(mapping[i] for i in train if i in mapping)
    test_dbs = Counter(mapping[i] for i in test if i in mapping)
    shared = set(train_dbs) & set(test_dbs)
    reachable = sum(count for db, count in test_dbs.items() if db in shared)

    print("\ndatabase coverage")
    print(f"  databases with >=1 train instance: {len(train_dbs)}/{len(set(mapping.values()))}")
    print(f"  databases present in both splits:  {len(shared)}")
    print(
        f"  test instances whose database has a train instance: "
        f"{reachable}/{len(test)} ({reachable / len(test):.0%})"
    )
    print("  (upper bound on how many test instances db-scoped rules can reach;")
    print("   the rest must rely on generic rules)")


if __name__ == "__main__":
    raise SystemExit(main())
